name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 자정 (UTC 기준)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: choyeounghyeon
      - name: Commit & Push
        run: |
          git config user.name choyeounghyeon
          git config user.email whdudgus0101@icloud.com
          git add -A .
          git commit -m "generated"
          git push
